const productos = [
  {
    "numero": 5896578,
    "codigo": "*5896578*",
    "producto": "Cheese Tris",
    "marca": "Frito Lay",
    "categoria": "Snack",
    "calorias": 540,
    "azucar": "Alto",
    "grasasSaturadas": "Alta",
    "sodio": "Alto",
    "proteinas": 6,
    "fibra": 3,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 35,
    "indiceNutricional": "E",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "1 vez/semana",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Alto en sodio y grasas saturadas.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Gra Nuts",
    "imagen": "https://alimentosselectos.cl/wp-content/uploads/2025/12/Cheese-Tris-FritoLay-120g-snack-de-queso.webp",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896579,
    "codigo": "*5896579*",
    "producto": "Doritos",
    "marca": "Frito Lay",
    "categoria": "Snack",
    "calorias": 510,
    "azucar": "Bajo",
    "grasasSaturadas": "Alta",
    "sodio": "Alto",
    "proteinas": 7,
    "fibra": 4,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 40,
    "indiceNutricional": "D",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "1 vez/semana",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Alto en sodio.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Pretzlet",
    "imagen": "https://i.pinimg.com/originals/31/85/63/31856301c181bceb667ac5cd6e8d033d.jpg",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896580,
    "codigo": "*5896580*",
    "producto": "Buck's Chips Sal de Mar",
    "marca": "Buck's",
    "categoria": "Snack",
    "calorias": 535,
    "azucar": "Bajo",
    "grasasSaturadas": "Alta",
    "sodio": "Alto",
    "proteinas": 6,
    "fibra": 3,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 38,
    "indiceNutricional": "E",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Alto en sodio.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Gra Nuts",
    "imagen": "https://tse1.mm.bing.net/th/id/OIP.b3s3KaOAWa3RVbuuhMJohgHaIS?pid=Api&P=0&h=180",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896581,
    "codigo": "*5896581*",
    "producto": "Buck's Chips Jalapeño",
    "marca": "Buck's",
    "categoria": "Snack",
    "calorias": 530,
    "azucar": "Bajo",
    "grasasSaturadas": "Alta",
    "sodio": "Alto",
    "proteinas": 6,
    "fibra": 3,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 38,
    "indiceNutricional": "E",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Alto en sodio.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Gra Nuts",
    "imagen": "https://metroio.vtexassets.com/arquivos/ids/520579/Papas-Inka-Chips-Sabor-Jalape-o-30G-PAPAS-INKA-CHIPS-JALAPE-O-30G-1-261842.jpg?v=638483890189070000",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896582,
    "codigo": "*5896582*",
    "producto": "Lay's",
    "marca": "Frito Lay",
    "categoria": "Snack",
    "calorias": 536,
    "azucar": "Bajo",
    "grasasSaturadas": "Alta",
    "sodio": "Alto",
    "proteinas": 7,
    "fibra": 4,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 40,
    "indiceNutricional": "D",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Alto en sodio.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Pretzlet",
    "imagen": "https://tse1.mm.bing.net/th/id/OIP.zcT9ZjOekS55W1kv5-oYXAHaHa?pid=Api&P=0&h=180",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896583,
    "codigo": "*5896583*",
    "producto": "Club Social",
    "marca": "Mondelez",
    "categoria": "Galleta",
    "calorias": 430,
    "azucar": "Medio",
    "grasasSaturadas": "Media",
    "sodio": "Medio",
    "proteinas": 8,
    "fibra": 2,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 62,
    "indiceNutricional": "C",
    "semaforoNutricional": "🟡",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "2-3 veces/semana",
    "beneficios": "Aporta proteínas.",
    "aspectosAConsiderar": "Sodio moderado.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Soda Field",
    "imagen": "https://tse2.mm.bing.net/th/id/OIP.INsqYKq2vnSOVPv5fNYc1wHaHa?pid=Api&P=0&h=180",
    "nivelSemaforo": 2
  },
  {
    "numero": 5896584,
    "codigo": "*5896584*",
    "producto": "Oreo",
    "marca": "Mondelez",
    "categoria": "Galleta",
    "calorias": 480,
    "azucar": "Alto",
    "grasasSaturadas": "Media",
    "sodio": "Medio",
    "proteinas": 5,
    "fibra": 2,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 55,
    "indiceNutricional": "D",
    "semaforoNutricional": "🟠",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "1 vez/semana",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Azúcar elevada.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Soda Field",
    "imagen": "https://www.onestop.co.uk/wp-content/uploads/b5f78208-d8bf-4235-9ccf-0d4b92a7d815.png",
    "nivelSemaforo": 2
  },
  {
    "numero": 5896585,
    "codigo": "*5896585*",
    "producto": "Ritz",
    "marca": "Mondelez",
    "categoria": "Galleta",
    "calorias": 500,
    "azucar": "Medio",
    "grasasSaturadas": "Media",
    "sodio": "Medio",
    "proteinas": 7,
    "fibra": 2,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 58,
    "indiceNutricional": "D",
    "semaforoNutricional": "🟠",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "1 vez/semana",
    "beneficios": "Fuente de energía.",
    "aspectosAConsiderar": "Grasas moderadas.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Crackelet",
    "imagen": "https://tse1.mm.bing.net/th/id/OIP.6A0H4Som-7HpoPslhp12DAHaHa?pid=Api&P=0&h=180",
    "nivelSemaforo": 2
  },
  {
    "numero": 5896586,
    "codigo": "*5896586*",
    "producto": "Trident",
    "marca": "Trident",
    "categoria": "Goma de mascar",
    "calorias": 170,
    "azucar": "Bajo",
    "grasasSaturadas": "Baja",
    "sodio": "Bajo",
    "proteinas": 0,
    "fibra": 0,
    "nivelSaludable": "🟢 Saludable",
    "puntuacion": 90,
    "indiceNutricional": "A",
    "semaforoNutricional": "🟢",
    "porcionRecomendada": "1 unidad",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Sin azúcar.",
    "aspectosAConsiderar": "No sustituye el cepillado.",
    "recomendacion": "Mejor opción que otros dulces.",
    "alternativaSaludable": "-",
    "imagen": "https://i.pinimg.com/736x/38/8c/c7/388cc78285f9d47bc1216f9c839c8d52.jpg",
    "nivelSemaforo": 3
  },
  {
    "numero": 5896587,
    "codigo": "*5896587*",
    "producto": "Milky Way",
    "marca": "Mars",
    "categoria": "Chocolate",
    "calorias": 450,
    "azucar": "Alto",
    "grasasSaturadas": "Alta",
    "sodio": "Bajo",
    "proteinas": 4,
    "fibra": 1,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 42,
    "indiceNutricional": "D",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "25 g",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Azúcar alta.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Gra Nuts",
    "imagen": "https://www.milkywaybar.com/cdn-cgi/image/width=472,height=472,f=auto,quality=90/sites/g/files/fnmzdf631/files/migrate-product-files/xmp7zfxjxvldw1ezcvym.png",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896588,
    "codigo": "*5896588*",
    "producto": "Field Cua Cua",
    "marca": "Field",
    "categoria": "Chocolate",
    "calorias": 470,
    "azucar": "Alto",
    "grasasSaturadas": "Alta",
    "sodio": "Bajo",
    "proteinas": 4,
    "fibra": 1,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 40,
    "indiceNutricional": "D",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "25 g",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Azúcar alta.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Gra Nuts",
    "imagen": "https://i0.wp.com/www.confiterialamundial.cl/wp-content/uploads/field-mini-cua-cua-42gr.jpg?fit=1000%2C1000&ssl=1",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896589,
    "codigo": "*5896589*",
    "producto": "Frugos Del Valle",
    "marca": "Del Valle",
    "categoria": "Bebida",
    "calorias": 45,
    "azucar": "Alto",
    "grasasSaturadas": "Baja",
    "sodio": "Bajo",
    "proteinas": 0,
    "fibra": 0,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 60,
    "indiceNutricional": "C",
    "semaforoNutricional": "🟡",
    "porcionRecomendada": "250 ml",
    "frecuenciaRecomendada": "2-3 veces/semana",
    "beneficios": "Hidrata.",
    "aspectosAConsiderar": "Azúcar elevada.",
    "recomendacion": "Revisar contenido de azúcar.",
    "alternativaSaludable": "Agua",
    "imagen": "https://tse1.mm.bing.net/th/id/OIP.FnauoguRucUThQ_CU_RcYgHaJo?pid=Api&P=0&h=180",
    "nivelSemaforo": 2
  },
  {
    "numero": 5896590,
    "codigo": "*5896590*",
    "producto": "Galletas Pícaras",
    "marca": "Field",
    "categoria": "Galleta",
    "calorias": 490,
    "azucar": "Alto",
    "grasasSaturadas": "Alta",
    "sodio": "Medio",
    "proteinas": 5,
    "fibra": 2,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 45,
    "indiceNutricional": "D",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Azúcar alta.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Crackelet",
    "imagen": "https://corporacionliderperu.com/45577-large_default/picaras-galletas-chocolate-x-320-gr-pack-x-8-un.jpg",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896591,
    "codigo": "*5896591*",
    "producto": "Galleta Tentación",
    "marca": "Field",
    "categoria": "Galleta",
    "calorias": 500,
    "azucar": "Alto",
    "grasasSaturadas": "Alta",
    "sodio": "Medio",
    "proteinas": 5,
    "fibra": 2,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 44,
    "indiceNutricional": "D",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Azúcar alta.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Crackelet",
    "imagen": "https://imagedelivery.net/4fYuQyy-r8_rpBpcY7lH_A/tottusPE/43205033_1/w=800,h=800",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896592,
    "codigo": "*5896592*",
    "producto": "Galletas Rellenitas",
    "marca": "Field",
    "categoria": "Galleta",
    "calorias": 485,
    "azucar": "Alto",
    "grasasSaturadas": "Alta",
    "sodio": "Medio",
    "proteinas": 5,
    "fibra": 2,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 45,
    "indiceNutricional": "D",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Azúcar alta.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Soda Field",
    "imagen": "https://c8.alamy.com/comp/RF4GT5/winneconne-wi-20-january-2019-a-package-of-galletas-rellenitas-cookies-from-peru-on-an-isolated-background-RF4GT5.jpg",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896593,
    "codigo": "*5896593*",
    "producto": "Galletas Morochas",
    "marca": "Field",
    "categoria": "Galleta",
    "calorias": 495,
    "azucar": "Alto",
    "grasasSaturadas": "Alta",
    "sodio": "Medio",
    "proteinas": 5,
    "fibra": 2,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 44,
    "indiceNutricional": "D",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Azúcar alta.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Crackelet",
    "imagen": "https://candylandperu.com/wp-content/uploads/2023/02/GALLETA-MOROCHAS-30G.webp",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896594,
    "codigo": "*5896594*",
    "producto": "Galletas Glacitas",
    "marca": "Field",
    "categoria": "Galleta",
    "calorias": 470,
    "azucar": "Alto",
    "grasasSaturadas": "Media",
    "sodio": "Medio",
    "proteinas": 5,
    "fibra": 1,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 58,
    "indiceNutricional": "C",
    "semaforoNutricional": "🟡",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "1 vez/semana",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Azúcar alta.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Soda Field",
    "imagen": "https://tse2.mm.bing.net/th/id/OIP.sjXOtjGx35tm3q5BpSFFzwHaHa?pid=Api&P=0&h=180",
    "nivelSemaforo": 2
  },
  {
    "numero": 5896595,
    "codigo": "*5896595*",
    "producto": "Soda Field",
    "marca": "Field",
    "categoria": "Galleta",
    "calorias": 440,
    "azucar": "Bajo",
    "grasasSaturadas": "Media",
    "sodio": "Alto",
    "proteinas": 9,
    "fibra": 2,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 68,
    "indiceNutricional": "C",
    "semaforoNutricional": "🟡",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "2-3 veces/semana",
    "beneficios": "Más proteína.",
    "aspectosAConsiderar": "Sodio elevado.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Crackelet",
    "imagen": "https://plazavea.vteximg.com.br/arquivos/ids/16382626-1000-1000/20282832.jpg?v=637970179203600000",
    "nivelSemaforo": 2
  },
  {
    "numero": 5896596,
    "codigo": "*5896596*",
    "producto": "Galletas Rellenitas",
    "marca": "Field",
    "categoria": "Galleta",
    "calorias": 475,
    "azucar": "Alto",
    "grasasSaturadas": "Media",
    "sodio": "Medio",
    "proteinas": 5,
    "fibra": 2,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 56,
    "indiceNutricional": "C",
    "semaforoNutricional": "🟡",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "1 vez/semana",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Azúcar alta.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Soda Field",
    "imagen": "https://c8.alamy.com/comp/RF4GT5/winneconne-wi-20-january-2019-a-package-of-galletas-rellenitas-cookies-from-peru-on-an-isolated-background-RF4GT5.jpg",
    "nivelSemaforo": 2
  },
  {
    "numero": 5896597,
    "codigo": "*5896597*",
    "producto": "Galleta Vainilla Field",
    "marca": "Field",
    "categoria": "Galleta",
    "calorias": 462,
    "azucar": "Alto",
    "grasasSaturadas": "Media",
    "sodio": "Medio",
    "proteinas": 7.3,
    "fibra": 2,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 60,
    "indiceNutricional": "C",
    "semaforoNutricional": "🟡",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "1 vez/semana",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Azúcar alta.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Soda Field",
    "imagen": "https://plazavea.vteximg.com.br/arquivos/ids/3641056-1000-1000/243940-1.jpg?v=637739725270270000",
    "nivelSemaforo": 2
  },
  {
    "numero": 5896598,
    "codigo": "*5896598*",
    "producto": "Cereal Bear",
    "marca": "Bear",
    "categoria": "Cereal",
    "calorias": 410,
    "azucar": "Medio",
    "grasasSaturadas": "Baja",
    "sodio": "Bajo",
    "proteinas": 6,
    "fibra": 5,
    "nivelSaludable": "🟢 Saludable",
    "puntuacion": 85,
    "indiceNutricional": "B",
    "semaforoNutricional": "🟢",
    "porcionRecomendada": "40 g",
    "frecuenciaRecomendada": "2-3 veces/semana",
    "beneficios": "Fuente de fibra.",
    "aspectosAConsiderar": "Revisar porciones.",
    "recomendacion": "Mejor opción.",
    "alternativaSaludable": "Gra Nuts",
    "imagen": "https://tse1.mm.bing.net/th/id/OIP.59yk0Qe5S5du7D8hJSk8ZgHaHa?pid=Api&P=0&h=180",
    "nivelSemaforo": 3
  },
  {
    "numero": 5896599,
    "codigo": "*5896599*",
    "producto": "Bucky Chifles",
    "marca": "Bucky",
    "categoria": "Snack",
    "calorias": 540,
    "azucar": "Bajo",
    "grasasSaturadas": "Baja",
    "sodio": "Alto",
    "proteinas": 6,
    "fibra": 5,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 48,
    "indiceNutricional": "D",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Fuente de fibra.",
    "aspectosAConsiderar": "Sodio alto.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Gra Nuts",
    "imagen": "https://tse3.mm.bing.net/th/id/OIP.LHDNU5iuFyfzt9BVviYcdAHaHa?pid=Api&P=0&h=180",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896600,
    "codigo": "*5896600*",
    "producto": "Cuates",
    "marca": "Barcel",
    "categoria": "Snack",
    "calorias": 520,
    "azucar": "Bajo",
    "grasasSaturadas": "Baja",
    "sodio": "Alto",
    "proteinas": 7,
    "fibra": 4,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 50,
    "indiceNutricional": "D",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Sodio alto.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Pretzlet",
    "imagen": "https://tse3.mm.bing.net/th/id/OIP.YfXVD-nQ4obnPku-AIfR8wAAAA?pid=Api&P=0&h=180",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896601,
    "codigo": "*5896601*",
    "producto": "Pretzlet",
    "marca": "Pretzlet",
    "categoria": "Snack",
    "calorias": 390,
    "azucar": "Bajo",
    "grasasSaturadas": "Baja",
    "sodio": "Alto",
    "proteinas": 10,
    "fibra": 3,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 72,
    "indiceNutricional": "B",
    "semaforoNutricional": "🟢",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "2-3 veces/semana",
    "beneficios": "Mayor proteína.",
    "aspectosAConsiderar": "Sodio alto.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Gra Nuts",
    "imagen": "https://tse4.mm.bing.net/th/id/OIP.R8HH_bGl9BwcPC2NqV_EgwHaHa?pid=Api&P=0&h=180",
    "nivelSemaforo": 3
  },
  {
    "numero": 5896602,
    "codigo": "*5896602*",
    "producto": "Halls",
    "marca": "Mondelez",
    "categoria": "Caramelo",
    "calorias": 390,
    "azucar": "Alto",
    "grasasSaturadas": "Baja",
    "sodio": "Bajo",
    "proteinas": 0,
    "fibra": 0,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 55,
    "indiceNutricional": "C",
    "semaforoNutricional": "🟡",
    "porcionRecomendada": "1 unidad",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Refresca el aliento.",
    "aspectosAConsiderar": "Azúcar alta.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Trident",
    "imagen": "https://amerikasepetim.com/storage/app/uploads/public/676/156/cf3/676156cf3bf29636553734.jpeg",
    "nivelSemaforo": 2
  },
  {
    "numero": 5896603,
    "codigo": "*5896603*",
    "producto": "Ole Ole",
    "marca": "Field",
    "categoria": "Chocolate",
    "calorias": 480,
    "azucar": "Bajo",
    "grasasSaturadas": "Baja",
    "sodio": "Medio",
    "proteinas": 5,
    "fibra": 2,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 65,
    "indiceNutricional": "C",
    "semaforoNutricional": "🟡",
    "porcionRecomendada": "25 g",
    "frecuenciaRecomendada": "1 vez/semana",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Consumir en porciones.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Gra Nuts",
    "imagen": "https://chocolates.com.pe/wp-content/uploads/2022/09/Banners-Destacada-OleOle-Peru-CNCH-768x446.jpg",
    "nivelSemaforo": 2
  },
  {
    "numero": 5896604,
    "codigo": "*5896604*",
    "producto": "Bimboletes",
    "marca": "Bimbo",
    "categoria": "Panificados",
    "calorias": 410,
    "azucar": "Medio",
    "grasasSaturadas": "Baja",
    "sodio": "Medio",
    "proteinas": 6,
    "fibra": 2,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 68,
    "indiceNutricional": "C",
    "semaforoNutricional": "🟡",
    "porcionRecomendada": "50 g",
    "frecuenciaRecomendada": "2-3 veces/semana",
    "beneficios": "Fuente de energía.",
    "aspectosAConsiderar": "Harinas refinadas.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Cereal Bear",
    "imagen": "https://tse2.mm.bing.net/th/id/OIP.t150YZhiHf7NrgRlaesZ3gHaHa?pid=Api&P=0&h=180",
    "nivelSemaforo": 2
  },
  {
    "numero": 5896605,
    "codigo": "*5896605*",
    "producto": "Sublime",
    "marca": "Nestlé",
    "categoria": "Chocolate",
    "calorias": 530,
    "azucar": "Medio",
    "grasasSaturadas": "Media",
    "sodio": "Medio",
    "proteinas": 6,
    "fibra": 3,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 48,
    "indiceNutricional": "D",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "25 g",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Calorías elevadas.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Gra Nuts",
    "imagen": "https://media.falabella.com/tottusPE/43331127_1/public",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896606,
    "codigo": "*5896606*",
    "producto": "Princesa",
    "marca": "Nestlé",
    "categoria": "Chocolate",
    "calorias": 525,
    "azucar": "Medio",
    "grasasSaturadas": "Media",
    "sodio": "Medio",
    "proteinas": 6,
    "fibra": 2,
    "nivelSaludable": "🔴 Poco saludable",
    "puntuacion": 48,
    "indiceNutricional": "D",
    "semaforoNutricional": "🔴",
    "porcionRecomendada": "25 g",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Calorías elevadas.",
    "recomendacion": "Consumir ocasionalmente.",
    "alternativaSaludable": "Gra Nuts",
    "imagen": "https://tse2.mm.bing.net/th/id/OIP.e1n3m2pzas8Dg8hukQvvLAHaHa?pid=Api&P=0&h=180",
    "nivelSemaforo": 1
  },
  {
    "numero": 5896607,
    "codigo": "*5896607*",
    "producto": "Crackelet",
    "marca": "Field",
    "categoria": "Galleta",
    "calorias": 470,
    "azucar": "Medio",
    "grasasSaturadas": "Baja",
    "sodio": "Medio",
    "proteinas": 7,
    "fibra": 2,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 70,
    "indiceNutricional": "B",
    "semaforoNutricional": "🟢",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "2-3 veces/semana",
    "beneficios": "Mayor proteína.",
    "aspectosAConsiderar": "Consumir en porciones.",
    "recomendacion": "Mejor opción que otras galletas.",
    "alternativaSaludable": "Soda Field",
    "imagen": "https://tse4.mm.bing.net/th/id/OIP.tCnCOo-T3YkpqGzQnKQxEwHaHa?pid=Api&P=0&h=180",
    "nivelSemaforo": 3
  },
  {
    "numero": 5896608,
    "codigo": "*5896608*",
    "producto": "Gra Nuts",
    "marca": "Gra Nuts",
    "categoria": "Snack de frutos secos",
    "calorias": 460,
    "azucar": "Bajo",
    "grasasSaturadas": "Baja",
    "sodio": "Medio",
    "proteinas": 8,
    "fibra": 6,
    "nivelSaludable": "🟢 Saludable",
    "puntuacion": 92,
    "indiceNutricional": "A",
    "semaforoNutricional": "🟢",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "2-3 veces/semana",
    "beneficios": "Rico en fibra y proteína.",
    "aspectosAConsiderar": "Alto aporte calórico.",
    "recomendacion": "Excelente opción.",
    "alternativaSaludable": "-",
    "imagen": "https://tse3.mm.bing.net/th/id/OIP.0XBAlu1oP19-8YMuvpV9vAHaE8?pid=Api&P=0&h=180",
    "nivelSemaforo": 3
  },
  {
    "numero": 5896609,
    "codigo": "*5896609*",
    "producto": "Chocodonas",
    "marca": "Field",
    "categoria": "Galleta",
    "calorias": 480,
    "azucar": "Medio",
    "grasasSaturadas": "Baja",
    "sodio": "Medio",
    "proteinas": 5,
    "fibra": 2,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 62,
    "indiceNutricional": "C",
    "semaforoNutricional": "🟡",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "1 vez/semana",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Azúcar moderada.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Crackelet",
    "imagen": "https://tse2.mm.bing.net/th/id/OIP.rOM_NvTzn0w_8Fk40JB_AgHaHa?pid=Api&P=0&h=180",
    "nivelSemaforo": 2
  },
  {
    "numero": 5896610,
    "codigo": "*5896610*",
    "producto": "Gretell",
    "marca": "Field",
    "categoria": "Galleta",
    "calorias": 470,
    "azucar": "Medio",
    "grasasSaturadas": "Baja",
    "sodio": "Medio",
    "proteinas": 5,
    "fibra": 2,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 62,
    "indiceNutricional": "C",
    "semaforoNutricional": "🟡",
    "porcionRecomendada": "30 g",
    "frecuenciaRecomendada": "1 vez/semana",
    "beneficios": "Aporta energía.",
    "aspectosAConsiderar": "Azúcar moderada.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Crackelet",
    "imagen": "https://tse2.mm.bing.net/th/id/OIP.wMdYFQbHFGq6Z9nF_UT90QHaHa?pid=Api&P=0&h=180",
    "nivelSemaforo": 2
  },
  {
    "numero": 5896611,
    "codigo": "*5896611*",
    "producto": "Bubbaloo Sparkies",
    "marca": "Bubbaloo",
    "categoria": "Goma de mascar",
    "calorias": 390,
    "azucar": "Alto",
    "grasasSaturadas": "Baja",
    "sodio": "Bajo",
    "proteinas": 0,
    "fibra": 0,
    "nivelSaludable": "🟡 Moderado",
    "puntuacion": 58,
    "indiceNutricional": "C",
    "semaforoNutricional": "🟡",
    "porcionRecomendada": "1 unidad",
    "frecuenciaRecomendada": "Ocasionalmente",
    "beneficios": "Sabor duradero.",
    "aspectosAConsiderar": "Azúcar elevada.",
    "recomendacion": "Consumir con moderación.",
    "alternativaSaludable": "Trident",
    "imagen": "https://tse4.mm.bing.net/th/id/OIP.G4TPAWM0xJVO2dWttQBk0gHaHa?pid=Api&P=0&h=180",
    "nivelSemaforo": 2
  }
];